"""
Usage: python examples/train_infilling_diffusion.py

Example script for training a diffusion language model on infilling-style
Lean proof data. The model learns to fill in missing tactics by denoising
MDM mask tokens embedded directly in the proof context.

Prerequisites:
1. Generate infilling dataset using create_infilling_dataset.py:
   python datasets/numina-math-lean/create_infilling_dataset.py \
       --parser raw --val-ratio 0.1 --seed 42

2. Install dependencies:
   pip install transformers peft datasets torch wandb

3. If using wandb logging, authenticate first:
   wandb login
"""

import os
from pathlib import Path
from peft import LoraConfig, TaskType
from lean_dojo_v2.trainer.diffusion_sft_trainer import InfillingDiffusionTrainer

# Paths to infilling dataset (generated by create_infilling_dataset.py)
# Adjust these paths based on your dataset location
train_path = Path("datasets/april/leandojo_infilling/train.train.json")
val_path = Path("datasets/april/leandojo_infilling/train.val.json")
output_dir = "outputs/infilling-mdm-7b-april"
wandb_project = os.getenv("WANDB_PROJECT", "infilling")
wandb_run_name = "infilling-mdm-7b-april"

# Optional: LoRA configuration for efficient fine-tuning
# Set lora_config = None for full fine-tuning (requires more GPU memory)
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
)

# Create trainer
trainer = InfillingDiffusionTrainer(
    model_name="inclusionAI/LLaDA-MoE-7B-A1B-Instruct",
    train_path=str(train_path),
    val_path=str(val_path) if val_path.exists() else None,
    output_dir=output_dir,
    epochs=3,
    batch_size=8,
    lr=2e-5,
    max_length=1024,
    mask_span_length=64,
    lora_config=lora_config,
    wandb_project=wandb_project,
    wandb_run_name=wandb_run_name,
    qual_log_every_n_steps=200,
    qual_num_samples_per_split=64,
)

# Explicitly keep tqdm enabled. If this is False, HF uses PrinterCallback
# which emits raw metric dicts each logging step.
trainer.training_args.disable_tqdm = False

# Run training
trainer.train()

print(f"\nModel saved to {output_dir}")
print("You can now use this model for inference with DiffusionProver.")
