"""
Usage: python examples/train_infilling_autoregressive.py

Example script for training an autoregressive language model on the
APRIL infilling dataset (created by create_infilling_dataset.py).
This trains the model to predict the missing tactic for a single <HOLE>.
"""

import os
from pathlib import Path

from peft import LoraConfig, TaskType

from lean_dojo_v2.trainer.infilling_sft_trainer import InfillingAutoregressiveTrainer

# Paths to infilling dataset (generated by create_infilling_dataset.py)
train_path = Path("datasets/april/leandojo_infilling/train.train.json")
val_path = Path("datasets/april/leandojo_infilling/train.val.json")
output_dir = "outputs/infilling-ar-qwen3-7b-april"
wandb_project = os.getenv("WANDB_PROJECT", "infilling-ar")
wandb_run_name = "infilling-ar-qwen3-7b-april"

# Optional: LoRA configuration for efficient fine-tuning
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
)

trainer = InfillingAutoregressiveTrainer(
    model_name="Qwen/Qwen3-7B",
    train_path=str(train_path),
    val_path=str(val_path) if val_path.exists() else None,
    output_dir=output_dir,
    epochs=3,
    batch_size=8,
    lr=2e-5,
    max_length=1024,
    max_new_tokens=128,
    non_thinking_mode=True,
    lora_config=lora_config,
    wandb_project=wandb_project,
    wandb_run_name=wandb_run_name,
)

# Keep tqdm progress bars and suppress raw metric dict logs.
trainer.training_args.disable_tqdm = False

trainer.train()

print(f"\nModel saved to {output_dir}")
print("You can now use this model for autoregressive infilling inference.")
